from abc import ABC, abstractmethod
from typing import List, Optional
from app.models import Product, ProductPatch

class Repository(ABC):
    @abstractmethod
    def create(self, p: Product) -> Product: ...
    @abstractmethod
    def get(self, id: str) -> Optional[Product]: ...
    @abstractmethod
    def list_all(self) -> List[Product]: ...
    @abstractmethod
    def patch(self, id: str, patch: ProductPatch) -> Optional[Product]: ...
    @abstractmethod
    def delete(self, id: str) -> bool: ...
